version: '3.8'

services:
  magiiv-app:
    build: .
    container_name: magiiv-app
    restart: unless-stopped
    ports:
      # Expõe a aplicação na porta 3000 externa (Mude a esquerda se houver conflitos, como "3012:3000")
      - "3000:3000"
    volumes:
      # ⚠️ MUITO ÚTIL: Protege seu banco de dados (SQLite) de ser deletado ao atualizar o app
      - magiiv-data:/app/.data
    env_file:
      # Diz ao docker para ler suas senhas de producao a partir de um arquivo chamado env.production (na VPS)
      - .env.production
    environment:
      - NODE_ENV=production

volumes:
  magiiv-data:
    name: magiiv_database_vol
